# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          keys: pip-cache

      - run:
          name: install dependencies
          command: |
            if [ ! -x venv ]; then
              python3 -m venv venv
            fi
            . venv/bin/activate
            pip config set global.progress_bar off
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - save_cache:
          key: pip-cache
          paths:
          - "~/.cache/pip"

      - run:
          name: sphinx
          command: |
            . venv/bin/activate
            make html
